# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Development Projects
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Web development projects I'm working on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: californiavol
github_username:  cgb37

github_url: http://github.com/cgb37
twitter_url: http://twitter.com/californiavol
google_plus_url: https://plus.google.com/u/0/+CharlesBrownRoberts
linkedin_url: https://www.linkedin.com/pub/charles-brown-roberts/32/547/303
website_url: http://charlesbrownroberts.com
feed_url: https://cgb37.github.io/feed.xml

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap


# standard jekyll configuration

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

permalink: /:title
highlighter: rouge
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor